name: env secrets

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Environment wise secrets. Select the Environment
        options: 
        - dev
        - stg
      
jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: dev secrets
      if: ${{ github.events.inputs == "dev" }
      run: echo ${{ secrets.dev_sec }}

    - name: stg secrets
      if: ${{ github.events.inputs == "stg" }}
      run: echo ${{ secrets.stg_sec }}	  
	  
	  