name: env secrets

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Environment wise secrets. Select the Environment
        options: 
        - dev
        - stage
      
jobs:
  dev:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENV }}
    steps:
    - name: dev secrets
      if: ${{ github.events.inputs.ENV == "dev" }
      run: echo ${{ secrets.SEC }}
      
  stage:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.ENV }}
    steps:
    - name: stg secrets
      if: ${{ github.events.inputs.ENV == "stage" }}
      run: echo ${{ secrets.SEC }}
