name: env secrets

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Environment wise secrets. Select the Environment
        options: 
        - dev
        - stage
      
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: dev secrets
      if: ${{ github.events.inputs == "dev" }
      run: echo ${{ secrets.SEC }}

    - name: stg secrets
      if: ${{ github.events.inputs == "stage" }}
      run: echo ${{ secrets.SEC }}
